
use_cross_validation: true
split_type: 'time_series'
n_splits: 5
scoring_metric: 'neg_mean_squared_error'  # Correct scoring metric
tuning: true  # Enable tuning
search_type: grid  # or 'random' for RandomizedSearchCV
random_search_n_iter: 20  # Only used if search_type is 'random'
n_jobs: -1
verbose: 2