use_cross_validation: true
split_type: 'time_series'
n_splits: 5
scoring_metric: 'neg_mean_squared_error'  # Correct scoring metric
tuning: true  # Enable tuning
search_type: random 
search_type_params:
 grid: {}
 random: {
  'n_iter': 4,  # Number of iterations for random search
  }  
n_jobs: -1
verbose: 2