
- type: Ridge
  params: {}
  scaling: true
  tuning_params: {}

- type: ExtraTreesRegressor
  params:
    n_estimators: 100
    max_depth: 10
    random_state: ${seed}
  tuning_params:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 20, 100]
    min_samples_split: [2, 5, 10]
  scaling: false

# - type: Ridge
#   params:
#     alpha: 1.0  # Default value
#     random_state: ${seed}
#   tuning_params:
#     alpha: [0.1, 1.0, 10.0, 100.0]
#   scaling: true
