# configs/shallow4.yaml

run:
  run_name: shallow4
  seed: &seed 42
  submit: false
  save_model: false
  gcloud: true

logging:
  mlflow_log: false
  tracking_tool: mlflow
  artifact_dir: artifacts/${run.run_id}
  
output:
  save_model: true
  output_folder: 'output'
  saved_models_folder: 'saved_models'
  saved_models_filename: 'best_model.pkl'
  saved_pipeline_filename: 'preprocessing_pipeline.pkl'
  combined_model_filename: 'combined_model.joblib'
  plots: false
  sample_submission_filename: 'sample_submission.csv'

mlflow:
  enabled: true
  experiment_name: "energy_forecasting"
  tracking_uri: "file:./mlruns" 

data:
  data_path: 'data/data_raw/'
  train_path: 'df_train.csv'
  test_path: 'df_test.csv'
  submission_path: 'sample_submission_load_shortfall.csv'
  target_column: load_shortfall_3h

preprocessing:
  column_to_impute: 'Valencia_pressure'
  imputer:
    type: TimeAwareKNNImputer
    params:
      n_neighbors: 5
  freq: '3h'
  add_time_dummies: 'cyclical'
  train_val_split: 0.2

models:
  - type: LinearRegression
    params: {}
    scaling: true

  - type: RandomForest
    params:
      n_estimators: 10
      random_state: *seed
    scaling: false
