# configs/energy_forecasting.yaml

run:
  run_name: shallow3_only_scikit
  seed: &seed 42
  submit: false
  mlflow_log: true

data:
  data_path: 'Data/Data_raw/'
  train_path: 'df_train.csv'
  test_path: 'df_test.csv'
  submission_path: 'sample_submission_load_shortfall.csv'
  target_column: load_shortfall_3h

preprocessing:
  imputer:
    type: TimeAwareKNNImputer
    params:
      n_neighbors: 5
  freq: '3h'
  fill_method: 'interpolate'
  add_time_dummies: 'cyclical'
  train_val_split: 0.2

models:
  - type: LinearRegression
    params: {}
    scaling: true

  - type: RandomForest
    params:
      n_estimators: 10
      random_state: *seed
    scaling: false

  # Linear models with regularization
  - type: Ridge
    params:
      alpha: 10.0
      random_state: *seed
    scaling: true

  - type: Lasso
    params:
      alpha: 1.0
      random_state: *seed
    scaling: true

  - type: ElasticNet
    params:
      alpha: 1.0
      l1_ratio: 0.5
      random_state: *seed
    scaling: true

  # Tree models
  - type: RandomForest
    params:
      n_estimators: 100
      max_depth: 10
      random_state: *seed
    scaling: false

  - type: ExtraTreesRegressor
    params:
      n_estimators: 100
      max_depth: 10
      random_state: *seed
    scaling: false

  - type: GradientBoostingRegressor
    params:
      n_estimators: 100
      max_depth: 4
      learning_rate: 0.1
      random_state: *seed
    scaling: false

  # Other models
  - type: KNeighborsRegressor
    params:
      n_neighbors: 8
    scaling: true

  - type: SVR
    params:
      kernel: 'rbf'
      C: 10.0
      gamma: 'scale'
    scaling: true

training:
  early_stopping_rounds: 10
  batch_size: 64    # alleen relevant voor neural nets
  epochs: 50        # idem

logging:
  tracking_tool: mlflow
  artifact_dir: artifacts/${run.run_id}

mlflow:
  enabled: true
  experiment_name: "energy_forecasting"
  tracking_uri: "file:./mlruns" 