# configs/energy_forecasting.yaml

run:
  run_name: shallow1_no_time_dummies
  seed: &seed 42
  submit: false
  mlflow_log: true

data:
  data_path: 'Data/Data_raw/'
  train_path: 'df_train.csv'
  test_path: 'df_test.csv'
  submission_path: 'sample_submission_load_shortfall.csv'
  target_column: load_shortfall_3h

preprocessing:
  imputer:
    type: TimeAwareKNNImputer
    params:
      n_neighbors: 5
  freq: '3h'
  fill_method: 'interpolate'
  add_time_dummies: None

models:
  - type: LinearRegression
    params: {}

  - type: RandomForest
    params:
      n_estimators: 10
      random_state: *seed

    # Linear models with regularization (good for seasonal dummies)
  - type: Ridge
    params:
      alpha: 10.0  # Higher alpha for many seasonal features
      random_state: *seed

  - type: Lasso
    params:
      alpha: 1.0  # Can do feature selection on seasonal dummies
      random_state: *seed

  - type: ElasticNet
    params:
      alpha: 1.0
      l1_ratio: 0.5
      random_state: *seed

  # Tree models (naturally handle seasonal interactions)
  - type: RandomForest
    params:
      n_estimators: 100  # More trees for seasonal patterns
      max_depth: 10
      random_state: *seed

  - type: ExtraTreesRegressor
    params:
      n_estimators: 100
      max_depth: 10
      random_state: *seed

  - type: GradientBoostingRegressor
    params:
      n_estimators: 100
      max_depth: 4
      learning_rate: 0.1
      random_state: *seed

  - type: XGBRegressor
    params:
      n_estimators: 100
      max_depth: 4
      learning_rate: 0.1
      random_state: *seed

  # Other models
  - type: KNeighborsRegressor
    params:
      n_neighbors: 8 # Match hourly blocks

  - type: SVR
    params:
      kernel: 'rbf'
      C: 10.0  # Higher C for complex seasonal patterns
      gamma: 'scale'

    # Time Series Models
  - type: MA1
    params: {}

  - type: MA2
    params: {}

  - type: SMA
    params:
      window: 8  # 24-hour window   


training:
  early_stopping_rounds: 10
  batch_size: 64    # alleen relevant voor neural nets
  epochs: 50        # idem

logging:
  tracking_tool: mlflow
  artifact_dir: artifacts/${run.run_id}

mlflow:
  enabled: true
  experiment_name: "energy_forecasting"
  tracking_uri: "file:./mlruns" 