# configs/energy_forecasting.yaml

run:
  run_name: test_config
  seed: &seed 42
  submit: false
  mlflow_log: true

data:
  data_path: 'Data/Data_raw/'
  train_path: 'df_train.csv'
  test_path: 'df_test.csv'
  submission_path: 'sample_submission_load_shortfall.csv'
  target_column: load_shortfall_3h

preprocessing:
  imputer:
    type: TimeAwareKNNImputer
    params:
      n_neighbors: 5
  freq: '3h'
  fill_method: 'interpolate'
  add_time_dummies: 'cyclical'
  train_val_split: 0.2

models:

  # Time Series Models
  - type: MA1
    params: 
      AR_order: 0
      difference_order: 1
      MA_order: 1
    scaling: false

  - type: AR
    params:
      AR_order: 1
      difference_order: 1
      MA_order: 0
    scaling: false

training:
  early_stopping_rounds: 10
  batch_size: 64    # alleen relevant voor neural nets
  epochs: 50        # idem

logging:
  tracking_tool: mlflow
  artifact_dir: artifacts/${run.run_id}
  plots: false

mlflow:
  enabled: true
  experiment_name: "energy_forecasting"
  tracking_uri: "file:./mlruns" 