name: Build and Deploy Model

on:
  push:
    branches: 
        - main
        - clean_code

  pull_request:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear potential credential variables
        run: |
          unset GOOGLE_APPLICATION_CREDENTIALS
          unset CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE

      # Authenticate to Google Cloud using Workload Identity
      - id: auth
        uses: google-github-actions/auth@v2.1.11
        with:
          workload_identity_provider: projects/791992711848/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: cloud-run-sa-energy-forecast-i@energy-forecast-467113.iam.gserviceaccount.com
          create_credentials_file: false  # Use Workload Identity Federation
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform

      # Set up gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: energy-forecast-467113
          enable: true  # ← Critical: enables gcloud auth using WIF

      # Build and push Docker image using Google Cloud Build
      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit \
            --region=europe-west4 \
            --tag=eu.gcr.io/energy-forecast-467113/energy-forecast-service:${{ github.sha }} \ 
            --service-account=cloud-run-sa-energy-forecast-i@energy-forecast-467113.iam.gserviceaccount.com

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy energy-forecast-service \
            --image=eu.gcr.io/energy-forecast-467113/energy-forecast-service:${{ github.sha }} \
            --region=europe-west4 \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=cloud-run-sa-energy-forecast-i@energy-forecast-467113.iam.gserviceaccount.com \
            --set-env-vars=MODEL_VERSION=v1 \
            --project=energy-forecast-467113

      # Optional: Clean up old revisions
      - name: Clean up old revisions
        run: |-
          gcloud run services update-traffic energy-forecast-service \
            --region=europe-west4 \
            --cleanup \
            --project=energy-forecast-467113