name: Build, Test, and Push Docker Image

on:
  workflow_dispatch:  # Only runs manually
#on:
 # push:
  #  branches:
   ##   - main
     # - clean_code
  #pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --prefer-binary -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          PYTHONPATH=. pytest   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/electricity_shortfall:latest


      # Add these steps AFTER your Docker build/push
      - name: Deploy to Cloud Run
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: energy-forecast-service
          image: eu.gcr.io/energy-forecast/energy-forecast-service:${{ github.sha }}
          region: europe-north1
          env_vars: MODEL_VERSION=v1
          project_id: energy-forecast-467113
          # No 'credentials' needed if using Workload Identity