name: Deploy to Cloud Run

on:
  push:
    branches: 
      - main 
      - clean_code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: energy-forecast-467113

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker eu.gcr.io
  
      - name: Build and Push Docker Image
        run: |-
          docker build -t eu.gcr.io/energy-forecast-467113/energy-forecast-service:${{ github.sha }} .
          docker push eu.gcr.io/energy-forecast-467113/energy-forecast-service:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy energy-forecast-service \
            --image=eu.gcr.io/energy-forecast-467113/energy-forecast-service:${{ github.sha }} \
            --region=europe-west4 \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=MODEL_VERSION=v1