name: Test code

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache uv package cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}

      - name: Install uv and create venv
        run: |
            python -m pip install --upgrade pip
            python -m pip install uv
            uv venv .venv
  
      - name: Activate venv and install dependencies
        run: |
            source .venv/bin/activate
            uv pip install -e ".[test]"

      - name: Run tests 
        run: |
          .venv/bin/python -m pytest src/tests \
            --ignore=src/tests/test_pipeline.py \
            --ignore=src/tests/test_training.py \
            --ignore=set/src/tests/test_predict.py \
            --disable-warnings