name: Test code

on:
  push:
    branches:
      - main
      - clean_code
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache uv package cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}
          # If using pyproject.toml: key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies with uv (editable + extras)
        run: |
          python -m pip install uv
          uv pip install -e ".[test]"

      - name: Run tests (skip heavy ones)
        run: |
          PYTHONPATH=. pytest src/tests \
            --ignore=src/tests/test_training.py \
            --ignore=set/src/tests/test_pipeline.py \ 
            --disable-warnings